-- Production ortamında demo müşteri verisi kullanılmaz.
-- İlk firma kaydı db/supabase-schema.sql içindeki idempotent insert ile oluşturulur.
-- Admin hesabı scripts/create-admin.mjs ile üretilen SQL üzerinden eklenmelidir.
